jakopako/goskyr

config.yml
main.go

Add filter option

---

config.yml
main.go

Change implementation of filter function

---

main.go

Parallelize crawling

---

config.yml
main.go

Add LocomotivClub

---

main.go

Mehrspur Events with month 'Mrz' not parsed correctly

---

main.go

Improve logging

---

config.yml
main.go

Fixes #43
refactor config
minor code changes

Add Botanique

---

config.yml
example-config.yml
main.go

Add Papiersaal

---

config.yml

Add LaCigale

---

config.yml
example-config.yml
main.go

Rename `loc` keys to `selector` in configuration yml

---

README.md
concerts-config.yml
scraper/scraper.go

Extend filtering mechanism

---

concerts-config.yml
scraper/scraper.go

Add Volkshaus

---

scraper/scraper.go

Filters don’t work as expected in all cases

---

README.md
concerts-config.yml
scraper/scraper.go

date fields sometimes don't have a consistent format even within one scraper/location

---

config-gen.yml
generate/config.go

bug in root selector extraction

---

README.md

Explain pagination in readme

---

automate/config.go

Autoextract bug with url https://www.koko.co.uk/whats-on

---

README.md

Fixes #169
Thanks to @khesperus for the wording.

Add description of `entire_subtree` param to readme

---

scraper/scraper.go

So far this allows an array of transformations to a date component. So far regex-replace is the only supports transformation type, but this could be expanded. It could also be applied to other field types.

Add configuration and functionality for transforming date components before futher processing

---

scraper/scraper.go

Enable extracting text for fields that have the same selector as the list item

---

automate/config.go

autoextract config for https://www.heldenbar.ch/programm/ doesn't generate working config

---

README.md
concerts-config.yml

Document ML capability

---

date/date.go
date/date_test.go
date/day_format.go
date/month_format.go

Add dutch to date auto format extraction + other fix

---

automate/config.go
date/date.go

auto date extraction sets date_location to CEST but this can't be parsed

---

date/date.go
date/date_test.go

Wrongly extracted time format for string "DOORS: 7:30PM"?

---

.github/workflows/go-tests.yml
go.mod
go.sum
scraper/scraper.go

I've tested this code for regressions, but the real venue site I was testing the new feature with is down with a 505, so my next step will be to add a unit test for this.

New JSON feature (minimal) with recommendations by @jakopako

---

scraper/scraper.go

I'm not sure if there's any complexity that I'm missing here, but this seems pretty straight-forward.

Added transform to ordinary text fields

---

scraper/scraper.go

Change default value for type url fields

---

.github/workflows/codeql-analysis.yml
.github/workflows/go-tests.yml
Makefile
README.md
fetch/fetcher.go
go.mod
main.go
output/api.go
output/file.go
output/stdout.go
scraper/scraper.go

Add debug flag - wip

---

scraper/scraper.go

Make default field values configurable

---

go.mod
main.go
ml/ml.go
output/api.go
scraper/scraper.go

Add option to generate summary

---

README.md
scraper/scraper.go
scraper/scraper_test.go

allow configuring a default for the date components.
